### ISSUE TITLE
"Buyable"-cvars

### ISSUE THREAD

**Issue by Bara** [Yeradon/ttt-awp-silent#1]
Ist meiner Meinung sinnlos, wenn price = 0 ist - dann wird dieses Feature nicht geladen/registiert.

**Comment by good-live** [comment]
#5

**Comment by Yeradon** [comment]
Wusste Ich noch gar nicht. Sollte man evtl. auf Werte < 0 setzen da man ansonsten keine gratis Items anbieten kann.

**Comment by Bara** [comment]
Man könnte -1 nehmen, da 0 bereits überall verwendet wird zum deaktivieren.
