### ISSUE TITLE
Möglicher Waffen-Spam

### ISSUE THREAD

**Issue by Bara** [Yeradon/ttt-awp-silent#3]
Es gibt kein Limit für S-AWP beim kaufen. Mit Bug Abusing (3rd-Plugin) könnte man unendlich AWPs kaufen.

Entweder die alte Waffe löschen (wenn es eine AWP war) - oder ein Kauf-Limit einbauen.

**Comment by good-live** [comment]
#5

**Comment by Yeradon** [comment]
Buylimit was added by @good-live.
