### ISSUE TITLE
TTT Tag & Buy Translation

### ISSUE THREAD

**Issue by Bara** [Yeradon/ttt-awp-silent#6]
Schau dir mal diese Zeilen an:
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp#L78-L85
https://github.com/Bara20/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt_c4_jihad.sp#L175-L179

Kann man die beiden Translations sparen.

**Comment by Yeradon** [comment]
Ja, aber Ich finde das der Tag auch übersetzbar sein sollte.

**Comment by Bara** [comment]
Sollte sich einrichten lassen, sofern ich wieder die Lust und vorallem die Zeit für TTT finde.
